languages:
  - en_US
  - pt_BR

 # Model providers and Language models supported
---
openai:
  gpt-4:
    interface="API"
ollama:
  gemma2:
    interface="ollama"
  qwen3:
      interface="ollama"



