languages:
  - en_US
  - pt_BR

 # Language models supported
---
openai:
  gpt-4:
    interface="API"
Google:
  gemma2:
    interface="ollama"
  qwen3:
      interface="ollama"


 # Language models supported
